/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    CalculationHistory: typeof import('./src/components/history/CalculationHistory.vue')['default']
    CalculationModal: typeof import('./src/components/modals/CalculationModal.vue')['default']
    GasSphere: typeof import('./src/components/visualization/GasSphere.vue')['default']
    KPIWidget: typeof import('./src/components/kpi/KPIWidget.vue')['default']
    NormativeControls: typeof import('./src/components/controls/NormativeControls.vue')['default']
    NotificationCenter: typeof import('./src/components/ui/NotificationCenter.vue')['default']
    PipelineCanvas: typeof import('./src/components/pipeline/PipelineCanvas.vue')['default']
    RouteCalculator: typeof import('./src/components/calculator/RouteCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
